# SPDX-License-Identifier: GPL-3.0-only

from .prompt_queue import (
    NODE_CLASS_MAPPINGS as PROMPT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .zip_output import (
    NODE_CLASS_MAPPINGS as ZIP_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as ZIP_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **PROMPT_NODE_CLASS_MAPPINGS,
    **ZIP_NODE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **PROMPT_NODE_DISPLAY_NAME_MAPPINGS,
    **ZIP_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./web"

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
]
